"""
voice.py

Different voices for the Egor interface.

Constants:
DRY: A standard computer interface. (dict of str: str)
EGOR: A classic servant of the mad scientist interface. (dict of str: str)
"""

DRY = {
	'__name__': 'DRY',
	'choose-alarm': '\nWhich alarm would you like to kill (return for none)? ',
	'choose-bad-count': 'Number of those combatants: ',
	'choose-bad-guy': 'Other combatant name: ',
	'choose-encounter': 'Please enter the encounter name: ',
	'choose-section': '\nWhich section would you like to view (return for none)? ',
	'choose-skill': 'Please enter the skill to roll a check for: ',
	'choose-table': '\nWhich table would you like to roll on? ',
	'confirm-aa-off': 'Auto-attack is off.',
	'confirm-aa-on': 'Auto-attack is on.',
	'confirm-ak-off': 'Auto-kill is off.',
	'confirm-ak-on': 'Auto-kill is on.',
	'confirm-campaign': 'The campaign at {} has been loaded.',
	'confirm-climate': 'The climate has been set to {}.',
	'confirm-condition': '{} now has the condition {}.',
	'confirm-encounter': '\nThe encounter has:',
	'confirm-hp': '{} now has {} HP.',
	'confirm-hp-temp': '{} now has {} HP and {} temporary HP.',
	'confirm-kill': '{} has been removed from the initiative order.',
	'confirm-load': 'The saved Egor system state has been loaded.',
	'confirm-note': 'The note was added to the system for later storage.',
	'confirm-passive': '{} rolled a {} for a total of {} (passive = {}).',
	'confirm-season': 'The season has been set to {!r}.',
	'confirm-store': 'The Egor system state has been stored.',
	'confirm-skill': '{} rolled a {} for a total of {}.',
	'confirm-time-var': 'The time variable {variable} was set to {value}.',
	'confirm-uncondition': '{} no longer has the condition {}.',
	'confirm-voice': 'Standard voice settings restored.',
	'confirm-weather': 'The weather roll has been set to {}.',
	'error-attack': '{} does not have an attack named {!r}.',
	'error-auto-attack': 'Invalid setting for auto-attack.',
	'error-auto-kill': 'Invalid setting for auto-kill.',
	'error-bad-count': 'Invalid count, please enter that creature again.',
	'error-choice': '\nInvalid choice.',
	'error-climate': 'The {!r} climate is an invalid climate.',
	'error-creature': 'No creature named {!r} was found.',
	'error-creature-enc': 'Only creatures in the SRD or the campaign files can be used in encounters.',
	'error-creature-ndx': 'Creature index out of range.',
	'error-culture': 'There is no {!r} culture in the campaign files.',
	'error-date-format': 'The current campaign calendar has no format named {!r}.',
	'error-enc-regex': 'There is no encounter matching that expression.',
	'error-enc-name': 'You must provide an encounter name.',
	'error-gender': 'The {} culture does not have {} gender or name type.',
	'error-git': 'You need to quit out of Egor to commit anything, dipshit.',
	'error-help': "I can't help you with that.",
	'error-match': 'No matches found.',
	'error-no-calendar': 'The current campaign does not have a calendar.',
	'error-no-campaign': 'There is no campaign loaded.',
	'error-option': 'Invalid option name: {!r}.',
	'error-personality': 'Invalid personality type: {}.',
	'error-roll': 'That is an invalid roll specification.',
	'error-season': '{!r} is an invalid season.',
	'error-table': 'There is no table named {!r}.',
	'error-table-regex': 'No matching tables were found.',
	'error-tag': 'The tag {!r} is not in any of the notes.',
	'error-time': 'The time string {!r} is not valid.',
	'error-uncondition': '{} did not have the condition {} to remove.',
	'error-voice': 'There is no voice named {!r} on file.',
	'failure-save': '{} failed the save with a {}.',
	'list-attacks': '{} has the following attacks:',
	'more-help': "Additional help topics available with 'help <topic>':",
	'more-tables': "You can list all known tables with 'table list'.",
	'new-ac': "{}'s armor class is now {} + {} = {}",
	'new-round': 'It is now Round {}',
	'prompt': 'EGOR >> ',
	'removed-alarm': 'The alarm has been removed.',
	'set-init': 'What is the initiative for {}? ',
	'set-init-bonus': 'What is the initiative bonus for {}? ',
	'success-save': '{} made the save with a {}.',
	'query-creature': 'Which {} (1-{})? ',
	'query-save': 'Save changes to the Egor system (y/n)? '
}

EGOR = {
	'__name__': 'EGOR',
	'choose-alarm': '\nWhich alarm would you like to kill, master (return for none)? ',
	'choose-bad-count': 'Number of villains: ',
	'choose-bad-guy': 'Villain name: ',
	'choose-encounter': 'What encounter would you like to use, master? ',
	'choose-section': '\nWhich scroll would you like to peruse, master? ',
	'choose-skill': 'Which skill would you like to test, master? ',
	'choose-table': '\nWhich oracle would you like to consult, master? ',
	'confirm-aa-off': 'Auto-attack is off, master. Ho hum.',
	'confirm-aa-on': 'Auto-attack is on, master. I eagerly await the chaos.',
	'confirm-ak-off': 'Auto-kill is off, master. Your mercy is boundless.',
	'confirm-ak-on': 'Auto-kill is on, master. Asmodeus will know his own.',
	'confirm-campaign': 'I have read the scrolls from {}, master.',
	'confirm-climate': 'I have set the tower to move to a {} climate, master.',
	'confirm-condition': '{} has been afflicted with the {} condtion, master.',
	'confirm-encounter': '\nExcellent choice, master. That encounter includes:',
	'confirm-hp': '{} now has {} HP, master.',
	'confirm-hp-temp': '{} now has {} HP and {} temporary HP, master.',
	'confirm-kill': '{} sleeps with the sahaugin, master.',
	'confirm-load': 'The game state has been restored, master.',
	'confirm-note': 'Your note has been added to the scroll, master.',
	'confirm-passive': '{} managed a {} for a total of {}, but they can do {} passively, master.',
	'confirm-season': 'I have moved the enchanted clock to {}, master.',
	'confirm-skill': '{} managed a {} for a total of {}, master.',
	'confirm-store': 'I have stored all of the incantations, master.',
	'confirm-time-var': 'I have set the time incantation {variable} to {value}, master.',
	'confirm-uncondition': '{} has been cured of the {} condtion, master.',
	'confirm-voice': 'I am ready to do your bidding, master.',
	'confirm-weather': 'The weather demons have been given the instruction {!r}, master.',
	'error-attack': '{} does not know how to {!r}, master.',
	'error-auto-attack': 'Auto-attack bit me when I tried to set it to that, master.',
	'error-auto-kill': 'Auto-kill refuses to be set to that, master.',
	'error-bad-count': 'I do not understand that count, master. Please enter that villain again.',
	'error-choice': '\nI am sorry, master, but that is not one of the available choices.',
	'error-climate': 'I do not recognize the climate {}, master.',
	'error-creature': 'I could not find a creature named {}, master.',
	'error-creature-enc': 'I do not know that creature, master.',
	'error-creature-ndx': 'There are not that many creatures in combat, master.',
	'error-culture': 'The {} culture was wiped out by a mad wizard centuries ago, master.',
	'error-date-format': 'The stupid calendar refuses to accept the {!r} format, master.',
	'error-enc-name': 'I cannot make an encounter without a name, master.',
	'error-enc-regex': 'I could not find any matching encounters, master.',
	'error-gender': 'The {} people do not have a {} gender, master, and got mad when I asked.',
	'error-git': 'I am Egor, master. I am not Git.',
	'error-help': "I do not know anything about that, master.",
	'error-match': 'I could not find anything matching that pattern, master.',
	'error-no-calendar': 'I am sorry, master, but the current campaign has no calendar.',
	'error-no-campaign': 'But you have not told me what campaign to load, master.',
	'error-option': 'I do not know any options named {}, master.',
	'error-personality': 'I have not heard of such a personality type, master.',
	'error-roll': "I do not know how to roll that, master.",
	'error-season': 'I do not know of a season named {}, master. Is it in the tabaxi calendar?',
	'error-table': 'I do not know of an oracle named {!r}, master.',
	'error-table-regex': 'I could not find a match oracle, master.',
	'error-tag': 'I do not know the tag {!r}, master.',
	'error-time': 'I do not understand the time {!r}, master.',
	'error-uncondition': 'But {} does not have the condition {}, master.',
	'error-voice': 'I do not know of any voice named {!r}, master.',
	'failure-save': '{} failed with a {}, master.',
	'list-attacks': 'These are the ways {} can kill you, master:',
	'more-help': "Additional help topics available with 'help <topic>':",
	'more-tables': "I can tell you all known oracles if you ask for 'table list', master.",
	'new-ac': "I added {1} to {2} to get {3} for {0}'s new armor class, master.",
	'new-round': 'We are now in round {}, master.',
	'prompt': 'Yes, master? ',
	'removed-alarm': '\nIt squeaked when I killed it, master.',
	'set-init': 'Master, what initiative should I use for {}? ',
	'set-init': 'Master, what initiative bonus should I use for {}? ',
	'success-save': '{} succeeded with a {}, master.',
	'query-creature': 'Which {}, master? There are {} of them. ',
	'query-save': 'But, master! The game state has changed! Shall I save it? '
}